apiVersion: 2018-06-01
location: '$(iotfactorykorea_location)'
name: KoreaFactory
properties:
  containers:
  - name: production-line-a
    properties:
      environmentVariables:
        - name: 'DEVICE_CERTIFICATE'
          value: '$(cert_korea_lineA)'
        - name: 'DPS_IDSCOPE'
          value: '$(IoTCentralDPS_ScopeID)'
        - name: 'PASSWORD'
          secureValue: '$(password_korea_lineA)'
      image: '$(iotfactorycontainerImageToDeploy)'
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 0.5
  - name: production-line-b
    properties:
      environmentVariables:
        - name: 'DEVICE_CERTIFICATE'
          value: '$(cert_korea_lineB)'
        - name: 'DPS_IDSCOPE'
          value: '$(IoTCentralDPS_ScopeID)'
        - name: 'PASSWORD'
          secureValue: '$(password_korea_lineB)'
      image: '$(iotfactorycontainerImageToDeploy)'
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 0.5
  osType: Linux
  imageRegistryCredentials:
  - server: '$(imageRegistryServer)'
    username: '$(imageRegistryUsername)'
    password: '$(imageRegistryPassword)'
tags: null
type: Microsoft.ContainerInstance/containerGroups